### PR TITLE
RFC: Stop self-registering

### PR DESCRIPTION
**Pull request by Rich-Harris**
Prompted by [this mailing list thread](https://groups.google.com/forum/#!topic/ractive-js/HwDxpGak3ic), and my own mixed experiences of moving from RequireJS to Browserify as a final step bundler, I've been  updating various plugins so that they no longer self-register. So [ractive-events-tap](https://github.com/ractivejs/ractive-events-tap), for example, has to be included like so:

```js
import Ractive from 'ractive';
import tap from 'ractive-events-tap';

let ractive = new Ractive({
  el: 'body',
  template: '<button on-tap='activate()'>tap me</button>',
  activate () { alert( 'activating' ); },
  events: { tap } // <-- must be explicitly registered
});
```

This eliminates a bunch of dependency headaches, and I've come round to thinking it's just a much better design.

This PR does the same thing for ractive-adaptors-backbone, but there's a wrinkle: because we need to be able to identify Backbone objects, and you can't really do that reliably with duck typing, there needs to be a Backbone reference available. If we eliminate the Backbone dependency, that means we need to pass in the reference somehow. Here's what I've gone with:

```js
import Ractive from 'ractive';
import Backbone from 'backbone';
import backboneAdaptor from 'ractive-adaptors-backbone';

// pass in reference, so we can identify models and collections 
backboneAdaptor.init( Backbone );

let ractive = new Ractive({
  el: 'body',
  template: '<h1>Hello {{user.name}}!</h1>',
  adaptors: [ backboneAdaptor ],
  data: {
    user: new Backbone.Model({ name: 'world' })
  }
});
```

What does everyone reckon? Is `adaptor.init(Backbone)` the right approach here (both for this and other similar cases)? (It self-registers if `window.Backbone` exists, i.e. we're in a `<script>` soup environment.)

Also, in line with other plugins, I moved everything to ES6 so that the UMD boilerplate sits outside the source code.

### CODE REVIEW

**Comment by martypdx** [comment]
I thought with peer dependencies the adaptor could import Backbone. Since it's running via browserify or amd, doesn't it resolve to same thing? Or am I off about that?

Otherwise, maybe `backboneAdaptor.Backbone = Backbone;` would be better pattern in case there are multiple dependencies.

Does inverting things help? I don't think so because thing calling into method below would still need to know what Backbone is, but thought I'd throw it out...

```js
let adaptor = {
	references ( acquire ) {
	    var refs = acquire.get(['Backbone']);
           Backbone = refs.Backbone;
	},
	filter ( object ) {
		...
	},
	wrap ( ractive, object, keypath, prefix ) {
		...
	}
};
```

**Comment by Rich-Harris** [comment]
AMD works that way, yeah. `peerDependencies` is a good solution on paper but the npm people have described it as their greatest mistake and are actively trying to undo the harm (as they perceive it) that it's caused - see e.g. https://github.com/npm/npm/issues/5080#issuecomment-40545599.

Also, with the dependency injection approach (is this an example of that? Did I use the terminology correctly?!) you can do this sort of thing, which is otherwise finicky if not impossible:

```js
adaptor.init(MyBackboneFork);

// or this, which I think I prefer now that you mention it
backboneAdaptor.Backbone = MyBackboneFork;
```

**Comment by martypdx** [comment]
I suspected all that to be the case. :)

> Also, with the dependency injection approach (is this an example of that? Did I use the terminology correctly?!)

I dunno, is it? ;p

One reason I thought of to use `.init( Backbone )` is this:

```js
init: function( ref ) {
    Backbone = ref;
    return this;
}

// now you can inline the init call
adaptors: [ backboneAdaptor.init( Backbone ) ],
```

**Comment by rstacruz** [comment]
@Rich-Harris, is this something that should be propagated to other ractive plugins too?

**Comment by Rich-Harris** [comment]
@rstacruz yep, I keep trying to find some time to go through them all (update the ones in the ractivejs org and send PRs for the rest on http://docs.ractivejs.org/latest/plugins). I've done a few so far, e.g. https://github.com/ractivejs/ractive-transitions-fade. Got a bit sidetracked by updating them to e.g. use ES6 modules and ditch grunt, neither of which are really the priority!

By the way, there was a discussion today on https://github.com/ractivejs/ractive-events-keys/pull/9 about what to do with plugins that create a bunch of different event handlers (ractive-touch being another obvious example).

Will get round to the others eventually but all help welcome obviously :)

**Pull request merged**
